fruits = ["banana" , "apple" , "mango" , "grape" , "orange"]
print(fruits)
fruits.append("Pineapple")
print(fruits)
fruits.remove("banana")
print(fruits)
fruits.extend(["papaya","watermelon"])
print(fruits)
fruits.insert(0,"apple")
print(fruits)
fruits.pop(3)
print(fruits)
fruits.sort(key=len)
print(fruits)
fruits.reverse()
print(fruits)
print(fruits.count("apple"))
